version: '3'

services:
  server1:
    build: ./servers
    ports:
      - "5001:5000"
    environment:
      - SERVER_ID=1
      - PORT=5000

  server2:
    build: ./servers
    ports:
      - "5002:5000"
    environment:
      - SERVER_ID=2
      - PORT=5000

  server3:
    build: ./servers
    ports:
      - "5003:5000"
    environment:
      - SERVER_ID=3
      - PORT=5000

  server4:
    build: ./servers
    ports:
      - "5004:5000"
    environment:
      - SERVER_ID=4
      - PORT=5000
